sudo: required
services: 
  - docker

before_install:
  - docker build -t yogeshjp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yogeshjp/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-923490531149"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  
